spring:
  application:
    name: Spring-Data-for-DDD-demo
  datasource:
    #    数据库配置信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/customerorder
    username: root
    password: 123456
  jpa:
    #     打印 sql
    show-sql: true